params:
  input_height: 256
  input_width: 512

  batch_size: 5
  epochs: 20000
  learning_rate: 0.001
  decay_steps: 1000
  decay_rate: 0.9

  ex_train:
    epochs: 30

  test:
    batch_size: 5
    epochs: 1

image:
  train_size: [512, 256]
  test_size: [512, 256]

path:
# Path config for raw dataset, train and test data
  # Root folders with src and processed images for train and test
  root:
    train: "data/train/"
    test: "data/test/"
    ex_train: "data/example/train/"
    ex_test: "data/example/test/"
  # Tusimple dataset and labels
  dataset:
    train: "train_set/"
    test: "test_set/"
    ex_train: "example_set/train/"
    ex_test: "example_set/test/"
  # Model weight folder
  models: "models/"
  # Image processing and preparing data dir
  image:
    src: "image/"
    binary: "binary/"
    instance: "instance/"
    results: "results/"
    ext: ".jpg"
  test_results: "test_results/"
  test:
    src: "image/"
    result: "result/"